### ISSUE TITLE
Category "New" with behaviour of "Hidden"

### ISSUE THREAD

**Issue by mase76** [quaap/LaunchTime#1]
Hi!
Great launcher! That replaced the shitty launcher on Fairphone open OS.
I suggest to place new installed apps in a category "New", that behaves like
the "Hidden" category. So the user could place the app from beginning without
searching where it was placed automatically.

**Comment by quaap** [comment]
Thanks! Interesting idea.  When a new app is installed, it would be placed into "New" which would then be visible in the side.  After it is empty, "New" disappears again.  I might look into that!

**Comment by mase76** [comment]
Yes, and you don't have to care about placing in the right category.
-- 
gpg-id: 383107c4
https://setho.org/people

**Comment by quaap** [comment]
I've added a configuration option to turn off the automatic categorization of new installs.  I didn't add a "New" category though: non-categorized apps will be added to "Other".  That could change, but I didn't want another special/protected category, at least not yet. Thanks for the idea!
