### ISSUE TITLE
Possibility of using LaunchTime as the standard drawer?

### ISSUE THREAD

**Issue by just-Nob** [quaap/LaunchTime#14]
I like the stock launcher of my LG G3, so I don't have the need to replace it by LaunchTime - but I'd like to use it as a replacement for the stock drawer! :) 
Up to now, I registered a gesture for calling LaunchTime, no matter which app is running currently in foreground. This it's pretty practical, but i.S. there also a possibility to register LaunchTime for a drawer app in Android, like it is done for a launcher app (i.e. the user gets asked decide which app to use when calling a drawer?

**Comment by quaap** [comment]
There's not a direct way like there is with registering launchers (that I can find).  Maybe an overlay or an appwidget thing?  Something to keep in mind for the future, but not a near-term goal.

**Comment by just-Nob** [comment]
What a pity... - hoped that Android had the possibility for registering apps as a drawer. :(
It's not only because of having an easy and quick possibility of calling LaunchPad (in fact, I'm using XPosed with the "Gesture Navigation" plug-in for calling LaunchTime anytime, no matter which app currently running in foreground), but also because it would have been an easy way to get rid of the system's stock drawer, because there's no way to get rid of the drawer icon in the system's stock launcher's QuickBar... ;P

Anyway, I've described an enhancement suggestion in issue #21 "Status list entry for opening LaunchTime"  as an alternative way for all users not being able to use Xposed,  but want to have a quick access to "only" a really good drawer with built-in category support,

**Comment by just-Nob** [comment]
Just checked out some drawers from Google Play Store... - none was able to register as a "standard drawer".
