### ISSUE TITLE
Sorting order for apps

### ISSUE THREAD

**Issue by just-Nob** [quaap/LaunchTime#15]
It's a nice possibility to drag and drop  the apps (inside every category) into the personally desired order, and I don't want to miss that.
Anyway, I'd like to switch to other assorting types as well:
(1) individual (the way it is done for now),
(2) alphabetically,
(3) first installation time,
(4) latest update time,
(5) most recent usage.

**Comment by quaap** [comment]
This was something I wanted to add anyway. It will be in the next release.

**Comment by mase76** [comment]
Could you make this sorting rules persistent, so that new added apps are sorted automatically?
At the moment, the apps are sorted once.
