### ISSUE TITLE
More than one category per app

### ISSUE THREAD

**Issue by just-Nob** [quaap/LaunchTime#18]
In most cases, it's practical to have only one category per app.
But there are a few apps that I'd like to assign to more than one category.
Why not to have more than one category per app, if desired (like in Apps2Org, for example)? This feature could be switchable in LaunchTime's settings (en-/disable).
If enabled, one could be asked whether to copy or move an app from one category to the other.

**Comment by quaap** [comment]
For the immediate future, I don't think this is going to happen.  I'm not ruling it out entirely down the road, but right now I don't think the benefit is worth the added complexity.

**Comment by quaap** [comment]
This should be added in the next release!

**Comment by EdenDorf** [comment]
Thanks alot :)
