### ISSUE TITLE
More colours and transparent

### ISSUE THREAD

**Issue by mase76** [quaap/LaunchTime#2]
Hi!
Please provide more colours and a transparent mode.

**Comment by quaap** [comment]
Yup!  I thought there should be options to change colors.  That options should appear in a later release. 

What do you mean by "transparent mode"?  Any existing examples?

**Comment by mase76** [comment]
I mean  the alpha of the background, that green one in your first release. When reducing to zero, only the text will be visible. Ok, white text could be invisible with light backgrounds. Maybe also make the text colour configurable.

Am 24. Januar 2017 20:13:50 MEZ schrieb Tom Kliethermes <notifications@github.com>:
>Yup!  I thought there should be options to change colors.  That options
>should appear in a later release. 
>
>What do you mean by "transparent mode"?  Any existing examples?

-- 
gpg-id: 383107c4
https://setho.org/people

**Comment by quaap** [comment]
A basic version of this will be in the next release. Nothing fancy, no "themes", just the ability to change the text and tab colors.  Thanks!

**Comment by mase76** [comment]
Works great! Thx!
