### ISSUE TITLE
Enhanced search capabilities

### ISSUE THREAD

**Issue by just-Nob** [quaap/LaunchTime#22]
Inspired by Quickdroid (which I'm regularly using - it's also available via f-droid), I suggest to enhance LaunchTime's search capabilities:
(1) Contacts,
(2) favorite websites,
(3) ...(?)
The affected kind of search results should be configurable in LaunchTime's settings (like it is in Quickdroid's settings ass well).

**Comment by quaap** [comment]
I considered that previously, but I'm not comfortable with all the nasty permissions needed to get that data.  If it turns out most people don't mind, I can add that later.

**Comment by just-Nob** [comment]
Ok, that's a point to think of.
Starting with Android 6 (or with Xposed/XPrivacy installed), the user will be asked to grant some of the permissions before they're given, so maybe this would be a way to go, if the search result types are optionally configurable in LaunchTime's settings (because the appropriate permissions aren't requested until the option is enabled in the settings)?

**Comment by EdenDorf** [comment]
Yeah i would like it to, that get added. Maybe there is some kind of a integration of QuickDroid if its installed to the device? So you can use normally and if QuickDroid is installed use its subroutine? Dont know if this would work.
