### ISSUE TITLE
App-updates with "Auto-categorize new apps" disabled

### ISSUE THREAD

**Issue by just-Nob** [quaap/LaunchTime#25]
When "Auto-categorize new apps" is disabled, the start-icons of updated apps were "pulled back" into the "others" category, even if they were beforehand sorted into another dedicated category.
Updated apps should always remain in their categories, independent of the "Auto-categorize new apps" status.

**Comment by quaap** [comment]
Yup, that was an oversight.  It should be working in the next release.
