### ISSUE TITLE
Jump automatically to the top category

### ISSUE THREAD

**Issue by mase76** [quaap/LaunchTime#3]
Hi!
To see a widget or favorite category per default, I suggest to move to the top category automatically after a timeout. Maybe 30s. Or the top category could be selected after screen unlocking.

**Comment by quaap** [comment]
That could definitely be an option.  Let me see how it fits with everything.  Thanks!

**Comment by quaap** [comment]
This functionality will be added in the next release.

**Comment by mase76** [comment]
Maybe the same for the quickbar, to return to the left?
