### ISSUE TITLE
Folders / sub categories

### ISSUE THREAD

**Issue by just-Nob** [quaap/LaunchTime#30]
I would appreciate to have folders or sub categories in each (main) category, for example to "sub-sort" all those utilities and tools, because I don't think that it's handy have half of a dozen "utility" (main) categories.

**Comment by phuyuk** [comment]
Me, too. For example: 

**Utilities
  -> Network
  -> Security
  -> Theming**

Too much like Windows Start Menu? (Is that a bad thing?)

**Comment by sebma** [comment]
@quaap Hi,

Why did you add the `wonfix` label to this feature request, is the existing API you're using not permitting to do so ?
