### ISSUE TITLE
Tabs: New Options

### ISSUE THREAD

**Issue by phuyuk** [quaap/LaunchTime#44]
1)  Please allow **_any_ tab to be assigned to the Home button** - regardless of vertical position in the tab list.

2)  Make the **'Search' tab optional** - I never use it and don't want to see it.

~~3)  Optionally allow **icons instead of text labels** for tabs. It may seem like I'm missing the utilitarian point of this launcher (I'm not), but for some categories, I really struggled to find meaningful text that would fit in the necessarily limited space.~~

Edit: Nope, text labels are intrinsic to the launcher's utilitarian charm. I respectfully withdraw request number 3.

**Comment by jw96** [comment]
Totaly agree with point 2. I know where exactly aps are, I dont need to searh them :p

**Comment by quaap** [comment]
I've been strapped for time and concentration ability due to my kids! :) I like these features but I don't know when I'd get to them.

**Comment by quaap** [comment]
I've just committed changes for point 2!  Should be in the next version. I actually generalized it by letting any tab be hidden via a checkbox on the "edit category" dialog. 

 As of now I'm not planning on implementing point 1... I'm not sure there's a big demand, or how to cleanly/easily handle the UI for changing it etc.  I'll keep it in mind for the future, though.  It may end up part of a larger feature.

Oh, for number 3, I know you withdrew it, but...  I had tried a long time ago to auto-generate a small image based on the first few apps in a category.  It worked, but made things look messier and didn't help me remember where things were all that much, so I abandoned it.  Is that what you mean?  I could consider reviving that as an optional feature if I can make it look OK / get the time. Or do you mean the user would hand-select app icons? Or images? etc?
