### ISSUE TITLE
Shortcuts created on file managers crash

### ISSUE THREAD

**Issue by rafael-morais** [quaap/LaunchTime#46]
Whenever I create shortcuts with file managers they are added to "other" categories. There is no problem about moving them to other tabs, but they won't work if touched. Whenever I try to open, the file manager will crash.

I've tried it on File Manager by Lenovo and Amaze File Manager.

**Comment by quaap** [comment]
I know it's been awhile but I think this one is finally fixed in 0.8.2.  Newly-created shortcuts, anyway.
