### ISSUE TITLE
Recently installed apps do not appear

### ISSUE THREAD

**Issue by thenktor** [quaap/LaunchTime#48]
Hi,

recently installed apps do not appear anywhere in the launcher on my device: Xiaomi A1, Android 8.0.0
After a system reboot they are there.

**Comment by thenktor** [comment]
I‘ve tried on another Xiaomi A1: It worked correctly before the Android O update and after the update it stopped working.

**Comment by quaap** [comment]
This will be fixed on a future update. Thanks!

**Comment by quaap** [comment]
This was fixed in the last release
