### ISSUE TITLE
Add an 'all' category

### ISSUE THREAD

**Issue by tetris4** [quaap/LaunchTime#5]
I think it would make sense to have a category listing for all applications, so one can use it in a more traditional way if they want to check for all the applications they have installed.

OT: I just installed LaunchTime from f-droid and love what you are doing with this launcher implementation! It feels very practical and responsive so far.

**Comment by quaap** [comment]
It's a possibility, but it needs to not get in the way.  I'll think it over. Thanks for the feedback!

**Comment by just-Nob** [comment]
I also would like to have an additional - maybe optional? - category for "all installed / available apps".
Thus Category souls be a "special" category like the search/recent one, and could possibly en-/disabled inn the settings. :) 
Especially (but not only!) useful after a new installed app that is sorted into a wrong category... ;)

**Comment by quaap** [comment]
I realized we can have this for free: I've added a wildcard character in the search box.  In the next version (0.3), typing a "." in the searchbox will list all packages.
