### ISSUE TITLE
Option to turn off badge, Add folder/separate, and a app columns issue

### ISSUE THREAD

**Issue by Crystal-RainSlide** [quaap/LaunchTime#58]
Those issues are about function, so I group them up.
Turn off badge to avoid disturbing;
Folder and separate widget allows 2 level grouping.

#### The columns issue:
My screen is 1080p and the density is 475dp.
On version .72 , when the sidebar width is set to small, I'll got 4 columns; but on higher verison of LaunchTime, it will be 3 columns any way.

Maybe we should get the width from the column number of app, and the icon size; further, allowing to set: column number, row number, icon size, text size, blank height between icon and text, sidebar width. Which requires a lot of work but solves everything, and gives lots of layout & Size option.

**Comment by quaap** [comment]
Thanks for reporting!  

In version 0.8 I've added a preference to disable unread counts / badges.  

I was/am calculating the number of columns, but even if I take screen density into account I still get different behaviors on different devices. I've just done some work re-calculating the number of columns, so hopefully now it will do the right thing by default in 0.8.  But if not, I've added preferences to force the number of columns.

Sub folders...  I don't use them and I think they get in the way.  I'm not opposed to them being a feature, but I'm probably not going to spend the time re-working the database to get them working.  Maybe in the future?
