### ISSUE TITLE
Possible GPL violation

### ISSUE THREAD

**Issue by patzzz** [quaap/LaunchTime#63]
Super Launcher is a launcher published in Google PlayStore and the screenshots are identical to LaunchTime:
https://play.google.com/store/apps/details?id=launcher.parallaxsoft.rocketlauncher

Apparently, it's LaunchTime with Ads.

Is this a GPL violation?

**Comment by quaap** [comment]
Thanks!  It is LaunchTime, and is not following the terms of the GPLv3 by not publishing their modified source code and not re-releasing it under the GPLv3.  It gives no indication of being open source. I filed a copyright claim with Google.  Thanks!  And it looks like they took a bunch of other GPL apps, too: https://play.google.com/store/apps/developer?id=Parallax+Soft+Inc
