### ISSUE TITLE
Translation to portuguese(pt-pt)

### ISSUE THREAD

**Issue by beiro** [quaap/LaunchTime#65]
So the app is tranlated to portuguese, don t know exactly wich one( there are two variants, pt-PT and pt-BR), but anyway, the present translation is so terrible, that even I do not understand 95% of the app settings. So i took some time to translate the strings to pt-PT, as a way of thanking for this great app.

[values.zip](https://github.com/quaap/LaunchTime/files/2206129/values.zip)

PS: a feature request( transparent status and navigation bar) :)

**Comment by quaap** [comment]
Thanks!
