### ISSUE TITLE
WeatherPro app empty widget

### ISSUE THREAD

**Issue by sunshinertoo** [quaap/LaunchTime#67]
when I add its widget it is empty.
On stock Android launcher it is OK

**Comment by quaap** [comment]
What's the package name or URL?  I see several apps named either "WeatherPro" or "Weather Pro". I tested one of the free ones and it worked, but I'm not sure we're testing the same thing.

**Comment by sunshinertoo** [comment]
On Mon, 23 Jul 2018 19:06:07 -0700
Tom Kliethermes <notifications@github.com> wrote:

> What's the package name or URL?  I see several apps named either
> "WeatherPro" or "Weather Pro". I tested one of the free ones and it
> worked, but I'm not sure we're testing the same thing.
> 
Hi Tom,

It is the WeatherPro by MeteoGroup Weather.

https://play.google.com/store/apps/details?id=com.mg.android

https://play.google.com/store/apps/dev?id=7282071594481600051

Arne

**Comment by quaap** [comment]
I can't seem to reproduce the behavior.  Version 0.8.2 does its widget-size calculations differently, and allows widget resizing, so hopefully it'll work once you upgrade. It's on Google Play, but F-Droid hasn't updated quite yet. Let me know if it starts working!

**Comment by sunshinertoo** [comment]
Hi Tom,

I upgraded to the newest versions (4.8.2 for Weather Pro Premium and
0.8.2 for LaunchTime)

Still the widget does not work.
The message "The application has encountered an unknown error." is
shown.

Hope this helps.

Thanks again for the very good LaunchTime!

Arne

**Comment by quaap** [comment]
I reworked widgets a bit in 0.8.3 (latest is 0.8.4).  Previously, a mistake on my part was creating new widgets instead on reusing the existing on in certain cases.  That should be fixed.

On the first start of the new LaunchTime versions, it should clear out any old widget resources that were leaked under the old version.  So hopefully that might fix your issue.

**Comment by sunshinertoo** [comment]
Hi Tom,

I installed version 0.8.4 and it works.
My favorite weather widget works!

Thank you so much!

greetings from Holland,

Arne
