### ISSUE TITLE
v0.8.1 App shortcuts do not show up

### ISSUE THREAD

**Issue by bilogic** [quaap/LaunchTime#72]
Hi,

When using apps to create a shortcut or icon, it does not show up in any of the tabs of LaunchTime.
e.g. Chrome. Thank you.

**Comment by quaap** [comment]
Very strange: I just fixed (hopefully) that problem today before I saw your report!  It should be in the next release, sometime in the next week or so, probably. 

As a caveat though, if you are on Android 8+, many apps which create shortcuts will not longer work: https://developer.android.com/reference/android/content/Intent#EXTRA_SHORTCUT_INTENT

Chrome-created shortcuts should work though.  And they work on my fixed version.

**Comment by bilogic** [comment]
Also, the way I tried to use LaunchTime is to have all the apps/icons in ```All``` category and create shortcuts in the various other categories. However, shortcuts of disabled apps do not re-appear when these apps are re-enabled.

The thinking is that if I forgot where an app was placed, I could go to ```All``` and find it. Any idea on how this could be handled in a more intuitive manner? Or perhaps have another special category that shows all apps/icons?

I'm on Android 6.0

**Comment by quaap** [comment]
Ah, yes, shortcuts would disappear when the target app is not present (uninstalled or disabled).  I could change that, but I'm not sure that's most people expected result. I'll see if there's anything I can change.

LaunchTime was intended to sort the apps into categories, but I added the search functionality to help 
you find the apps.  If you type a single dot (.), it will list all apps.

If I come up with a more generic solution I might write something up.
