### ISSUE TITLE
pressing home button obscures home icons

### ISSUE THREAD

**Issue by tmcl** [quaap/LaunchTime#73]
pressing the home button replaces the dock with the configuration panel. but of the home button several times should get the system into a known and consistent state, so if I press it two or three times I should know exactly where to move my finger (without looking at the screen) to obtain a certain frequent activity. the dock icons are important to this, since I put them there precisely because I want to use them frequently.

on the other hand, configuration is a rare process, since it's not wanted when the user is satisfied. so perhaps the "up" icon should more clearly indicate that it leads to configuration, but the home button shouldn't hide a frequent activity with infrequently used tools

thanks. I'm generally most pleased with launch time; it's much more user friendly than the standard style launchers

**Comment by quaap** [comment]
Hi.  Which version of LaunchTime do you have?  I messed up that with version 0.8, and partially fixed it in 0.8.1.  However, some configurations it still shows up a lot. Pressing the home button or back button should most definitely close the bar. Version 0.8.2, which I just released, hopefully fixes all of those problems.  It hasn't hit F-Droid yet (should be soon), but it is on Google Play.

**Comment by tmcl** [comment]
I have version 0.8.1 from F-Droid. I’m pleased to hear it should be fixed in Version 0.8.2.
