### ISSUE TITLE
Calendar widgets, only header bar

### ISSUE THREAD

**Issue by slipslider** [quaap/LaunchTime#74]
180801 latest Launchtime v has reduced calendar widgets to header bar only. ie not showing appointments...
Using Acalendar+ (on gcal) in Android 6.1
Please fix. Thanks, Boo

**Comment by quaap** [comment]
Hi!  From the "180801", I assume you have version 0.8.0?  If so, I have good news.  Version 0.8.1 out a few weeks fixes/changes some widget behavior, but version 0.8.2, just released, should calculate the proper widget size much better, and also (finally) supports widget resizing.  The version is already up on Google Play, and should be available through F-Droid when they build the index next, which should be very soon.
