### ISSUE TITLE
v0.8.2 widget settings not restored after reboot

### ISSUE THREAD

**Issue by bilogic** [quaap/LaunchTime#75]
Hi,

I have a few widgets which do not get their settings restored after a reboot. 1 of them is ```Shortcut Image```: https://play.google.com/store/apps/details?id=jp.windbellrrr.widget.shortcutimage

I tested this widget in Lightning launcher and its settings was restored. That led me to suspect the issue might lie with LaunchTime. Thank you.

**Comment by quaap** [comment]
Hi, thanks for reporting!  I think I've tracked down the issue: The widget was being created each time instead of loading via the id.  I've tested with jp.windbellrrr.widget.shortcutimage and it seems to maintain the image across restarts.  The fix will be in the next release.

**Comment by bilogic** [comment]
Happy to do all the testing and reporting! And grateful you are fixing them!
