### ISSUE TITLE
v0.8.2 behavior of icon tint

### ISSUE THREAD

**Issue by bilogic** [quaap/LaunchTime#80]
Hi,

When ```icon tint``` is set to full RGB and brightness but 0 transparency, icons show up as gray scale.
When transparency is set to 1, icons show in full color with no tinting
As transparency approaches full, icons show in full color gradually become more and more transparent

I was expecting transparency to adjust the mix between white (full RGB) and the original icon colors. 

Is the current ```icon tint``` behavior correct? Thank you.

**Comment by quaap** [comment]
Oh yeah, I forgot about that.  Most color tinting worked with simple colorfilters, but to get a true gray-scale, I had to add a special function that was triggered with the settings you mentioned.  I always meant to get back to it but eventually forgot (I wasn't even sure anyone actually used icon tinting).  I will put it back on my radar to see if there's some way to make it work smoothly.

**Comment by bilogic** [comment]
The industrial term from photoshop is ```hue``` and ```saturation```, should make it easier to find the relevant code examples. Original icons are too colorful, all trying to get your attention. Gray-scale made them too homogeneous that it was hard to do a color search by eye. Lower saturation will fix it. :)

Do you know if widgets can be de-saturated too?
