### ISSUE TITLE
v0.8.3 Add Widget becomes hidden

### ISSUE THREAD

**Issue by bilogic** [quaap/LaunchTime#84]
Hi,

Checking ```Extra menu actions``` causes ```Sort Category```, ```Add widgets``` etc to disappear. Is this by design? Thank you.

**Comment by quaap** [comment]
Ooh, I meant to have a small Toast appear the first few times people clicked the up arrow, but I got busy and it slipped my mind.  Long-click on a category to see those options. Each action applies to the category you long-click. "Add category" will add the new category directly after the one clicked.

**Comment by bilogic** [comment]
Haha cool! In that case, may I suggest removing the up arrow when ```Extra menu actions``` is checked? It only provides access to LaunchTime config which is available via Search or maybe add it to the pop up of every category. IMO, it will improve the aesthetics. Thank you.
